openapi: "3.0.1"
info:
  title: "url-expander-api"
  description: "API for URL Expander service"
  version: "2025-11-08T19:54:37Z"
servers:
- url: "https://e4lqku9uee.execute-api.ap-southeast-3.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "v1"
paths:
  /url-mappings:
    post: {}
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /users/me/urls:
    get:
      security:
      - CognitoAuthorizer: []
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /url-mappings/{expanded_code}:
    get:
      parameters:
      - name: "expanded_code"
        in: "path"
        required: true
        schema:
          type: "string"
    options:
      parameters:
      - name: "expanded_code"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
components:
  securitySchemes:
    CognitoAuthorizer:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "cognito_user_pools"
